### ISSUE TITLE
The slowness due to unreliability - Please work on bug report

### ISSUE THREAD

**Issue by RoundSparrow** [erbbysam/webRTCCopy#13]
Hey - there is an open bug on the reliability issues, and perhaps we need to define the issue in different ways.

Can you please come participate at https://code.google.com/p/webrtc/issues/detail?id=2270

I linked back to your project and comments about queue problems (having to wait for response from peer).

**Comment by erbbysam** [comment]
Thanks for the heads up, I added a comment.
-Sam

**Comment by RoundSparrow** [comment]
Thanks for jumping in. I figured you can provide more details, and I see you are currently active on your project.

One more thing: Opera Beta works with WebRTC - it's build on Chrome engine - you might want to update your readme. DataChannel works fine - and I often use it as a way to run mixed version testing.

**Comment by erbbysam** [comment]
Cool, thanks! I'll look into testing that & updating the readme/site later tonight.

**Comment by erbbysam** [comment]
Opera just worked with no code modifications needed, cool, & in it's current stable state can communicate with Chrome via the datachannel.

https://github.com/erbbysam/webRTCCopy/commit/e5af5714a93f41393cd171af877aae38af1def67

Closing this for now, going to create a new bug in the future to update the sites compatibility check & file chunk transfer size code.
Thanks,
Sam
