### ISSUE TITLE
Would you think about removing the google analytics?

### ISSUE THREAD

**Issue by melvincarvalho** [erbbysam/webRTCCopy#7]
So that privacy can be increased?

**Comment by erbbysam** [comment]
Following the discussing here - https://news.ycombinator.com/item?id=6579923 , this does leak the room name to Google Analytics, so I'm going to remove it.
Thanks,
Sam

**Comment by erbbysam** [comment]
https://github.com/erbbysam/webRTCCopy/commit/c1f35404414d633ea211050ff5e1085fc8d92308
