### ISSUE TITLE
Move to GPL

### ISSUE THREAD

**Issue by Miserlou** [erbbysam/webRTCCopy#9]
Love the project, but CC-BY-SA is an inappropriate license for a software project. May I suggest the GNU General Public License instead?

**Comment by ghost** [comment]
Why is a CC license inappropriate?

**Comment by Miserlou** [comment]
The main reason is that it isn't compatible with other open source licenses (because it is a license for text and assets, not for code). The GPL is essentially the same as CC-BY-SA, but it is the standard copyleft license.

On their website, Creative Commons explicitly state that: "Creative Commons licenses should not be used for software. We strongly encourage you to use one of the very good software licenses which are already available. We recommend considering licenses made available by the Free Software Foundation or listed at the Open Source Initiative. Unlike our licenses, which do not make mention of source or object code, these existing licenses were designed specifically for use with software. Furthermore, our licenses are not compatible with the GPL, the most frequently used free software license."

More info here: http://wiki.creativecommons.org/Frequently_Asked_Questions#Can_I_apply_a_Creative_Commons_license_to_software.3F

PS please join the WebP2P discussion group to announce this! http://webp2p.org

**Comment by erbbysam** [comment]
Thanks for the feedback, you're 100% correct that this license is less than ideal.

I've always been a huge fan of CC, which is why I used the license. I'll relicense everything here asap.
Thanks,
Sam

**Comment by ghost** [comment]
I also think that GPL is less than ideal, but it's really up to you and the
goals for your project.

**Comment by gleitz** [comment]
Another option would be the [MIT License](https://en.wikipedia.org/wiki/MIT_License). If you would like an overview of the differences visit [tldrlegal](http://bit.ly/19Y1oqo).

**Comment by erbbysam** [comment]
Ended up settling on the GPLv3 license. I believe everything should be in order now. Thanks for your help!
-Sam
